### PR TITLE
Changed banner styling in index.html

### PR DESCRIPTION
**Pull request by FeynmanTesla**
moved banner styling to CSS, and gave it absolute size and positioning

### CODE REVIEW

**Comment by Nambaseking01** [comment]
Wow, thanks! I was just playing around with the CSS trying to get things right and you just come like an angel trying to help! Will merge this to the master branch.

Thank you so much,
-The SUCS Team-

**Comment by FeynmanTesla** [comment]
> Wow, thanks! I was just playing around with the CSS trying to get things right and you just come like an angel trying to help! Will resolve the conflicts.
> 
> Thank you so much,
> -The SUCS Team-

Aha no problem. If it's not exactly what you want just let me know and I can make another pull request fixing whatever else you guys need done!

**Comment by Nambaseking01** [comment]
Oh, but this is not perfect. We need the banner's width to exactly fit inside the website's width.

Thank you,
-The SUCS Team-

**Comment by Nambaseking01** [comment]
Hello! Would you like to be a collaborator in this repository? If you do, I could send you an invite! 

Thank you,
-The SUCS Team-

**Pull request merged**
