### PR TITLE
add header

### PR DESCRIPTION
**Pull request by jbrow78**

### CODE REVIEW

**Comment by Nambaseking01** [comment]
Congratulations on creating the first pull request! We expect you to do great things and change our website marvellously! Also, adding a header is a nice idea but I am wondering whether it should be permanent or not. Maybe we will remove it when we have CSS to make the viewer easily understand.

Great job, Jay!
-The SUCS Team-

**Comment by jbrow78** [comment]
@

**Comment by Nambaseking01** [comment]
Unfortunately, it seems like you have not merged this commit into the master branch. Please retry to get this feature up and running!

Thank you,
-The SUCS Team-

**Comment by Nambaseking01** [comment]
We already have one now as described in issue #10, so thank you for trying to help!

Have a nice day,
-The SUCS Team-

**Pull request closed without merging**
